import os

TC_BASE_1 = os.getenv("TC_BASE_1")
SM_BASE_1 = os.getenv("SM_BASE_1")
SIMULATION_BASE_1 = os.getenv("SIMULATION_BASE_1")
MONGO_HOST_1 = os.getenv("MONGO_HOST_1")
MONGO_NAME_1 = os.getenv("MONGO_NAME_1")

TC_BASE_2 = os.getenv("TC_BASE_2")
SM_BASE_2 = os.getenv("SM_BASE_2")
SIMULATION_BASE_2 = os.getenv("SIMULATION_BASE_2")
MONGO_HOST_2 = os.getenv("MONGO_HOST_2")
MONGO_NAME_2 = os.getenv("MONGO_NAME_2")

SIMULATION_DATABASE_HOST = os.getenv("SIMULATION_DATABASE_HOST")
SIMULATION_DATABASE_PORT = os.getenv("SIMULATION_DATABASE_PORT")
SIMULATION_DATABASE_USER = os.getenv("SIMULATION_DATABASE_USER")
SIMULATION_DATABASE_PASSWORD = os.getenv("SIMULATION_DATABASE_PASSWORD")

MONGO_USER = os.getenv("MONGO_USER")
MONGO_PASSWORD = os.getenv("MONGO_PASSWORD")
